import { useMemo, useState } from "react";
import axios from "axios";
import { ArrowRight, ChefHat, CircleHelp, Instagram, MessageCircle, Minus, Plus, ShoppingBag, Sparkles, WandSparkles, X } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const products = [
  { id: "chocolate-cake", name: "Chocolate Celebration Cake", price: 1200, serves: "6–8", image: "https://images.unsplash.com/photo-1700448293876-07dca826c161?auto=format&fit=crop&w=900&q=85", story: "The cake you bring when the room deserves a little more chocolate." },
  { id: "cinnamon-rolls", name: "Cinnamon Rolls", price: 650, serves: "4–6", image: "https://images.unsplash.com/photo-1694632288834-17d86b340745?auto=format&fit=crop&w=900&q=85", story: "The box that makes an ordinary afternoon smell like a Sunday morning." },
  { id: "banana-loaf", name: "Chocolate Chip Banana Loaf", price: 750, serves: "6–8", image: "https://images.unsplash.com/photo-1621994214182-f467e6999dc9?auto=format&fit=crop&w=900&q=85", story: "A tender little loaf for slow tea, second slices and a warm kitchen." },
  { id: "brownies", name: "Fudge Brownie Box", price: 550, serves: "4–6", image: "https://images.unsplash.com/photo-1642453031286-8991becafe19?auto=format&fit=crop&w=900&q=85", story: "Dense, fudgy and gone before you remember to save one for later." }
];
const occasions = ["Birthday", "Tea party", "Gift", "Anniversary", "Family gathering", "Just craving something"];
const moods = ["Chocolate lover", "Fresh & citrusy", "Warm & comforting", "Coffee lover", "Something different"];

function App() {
  const [occasion, setOccasion] = useState("Tea party"); const [mood, setMood] = useState("Warm & comforting");
  const [people, setPeople] = useState(6); const [budget, setBudget] = useState(1000); const [dietary, setDietary] = useState("No preference");
  const [match, setMatch] = useState(null); const [loading, setLoading] = useState(false); const [cart, setCart] = useState([]); const [chatOpen, setChatOpen] = useState(false);
  const [message, setMessage] = useState(""); const [chat, setChat] = useState([{ role: "assistant", text: "Tell me who you’re baking for, and I’ll find the sweet spot." }]);
  const box = useMemo(() => products.reduce((sum, p, i) => sum + (i === 0 ? 1 : i === 1 ? 2 : i === 2 ? 1 : 2) * p.price / (i === 0 ? 1 : i === 1 ? 3 : i === 2 ? 1 : 4), 0), []);
  const addToCart = (product) => setCart((items) => [...items, product]);
  const runMatch = async () => { setLoading(true); try { const r = await axios.post(`${API}/match`, { occasion, mood, people, budget, dietary }); setMatch(r.data); } catch { setMatch({ product: products[2], explanation: "This warm, homemade pick feels just right for your gathering." }); } finally { setLoading(false); } };
  const surprise = () => { const picked = products[Math.floor(Math.random() * products.length)]; setMatch({ product: picked, explanation: "A little baker’s instinct says this is the one you didn’t know you were craving." }); document.getElementById("match-result")?.scrollIntoView({ behavior: "smooth" }); };
  const sendChat = async () => { if (!message.trim()) return; const text = message; setMessage(""); setChat((c) => [...c, { role: "user", text }]); try { const r = await axios.post(`${API}/chat`, { message: text }); setChat((c) => [...c, { role: "assistant", text: r.data.reply }]); } catch { setChat((c) => [...c, { role: "assistant", text: "I’m having a flour-covered moment. Try asking me again in a little while." }]); } };
  const whatsapp = () => { const text = `Hello Treats & Temptation by SK! I'd like to order: ${cart.map((p) => p.name).join(", ") || match?.product.name || "a recommendation"}.`; window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank"); };
  return <div className="site-shell">
    <nav className="nav"><a className="brand" href="#top" data-testid="brand-home"><span className="brand-mark">SK</span><span>Treats &<br /><b>Temptation</b></span></a><div className="nav-links"><a href="#match" data-testid="nav-match">Find your bake</a><a href="#box" data-testid="nav-box">Build a box</a><a href="#stories" data-testid="nav-stories">Bake stories</a></div><button className="icon-button" onClick={() => setChatOpen(true)} data-testid="open-baker-chat" aria-label="Open baker chat"><MessageCircle size={21} /></button><button className="cart-pill" onClick={() => document.getElementById("box").scrollIntoView({ behavior: "smooth" })} data-testid="cart-button"><ShoppingBag size={18} /> {cart.length || "Your box"}</button></nav>
    <main id="top">
      <section className="hero"><div className="hero-copy"><p className="eyebrow">HOMEMADE, MATCHED TO THE MOMENT</p><h1>Find the bake<br /><em>you feel like.</em></h1><p className="hero-text">Not sure what to order? Tell us the occasion, the mood and who’s coming. We’ll make the sweet decision easy.</p><div className="hero-actions"><a href="#match" className="button primary" data-testid="hero-find-bake">Find my perfect bake <ArrowRight size={17} /></a><button className="button text-button" onClick={surprise} data-testid="hero-surprise-button"><WandSparkles size={17} /> Surprise me</button></div><div className="hero-note"><Sparkles size={16} /> Baked in small batches, chosen with care</div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1700448293876-07dca826c161?auto=format&fit=crop&w=1300&q=85" alt="Homemade chocolate cake" data-testid="hero-dessert-image" /><div className="image-stamp">made for<br /><b>your moment</b></div></div></section>
      <section className="match-section" id="match"><div className="section-intro"><p className="eyebrow">01 / THE DESSERT MATCHMAKER</p><h2>Let’s find your<br /><em>perfect match.</em></h2><p>A few little questions, then a recommendation that feels like it was made for you.</p></div><div className="match-form"><div className="question"><label>Who are you buying for?</label><div className="choice-grid">{occasions.map((x) => <button className={occasion === x ? "choice active" : "choice"} onClick={() => setOccasion(x)} data-testid={`occasion-${x.toLowerCase().replaceAll(" ", "-")}`} key={x}>{x}</button>)}</div></div><div className="question"><label>What’s your mood?</label><div className="choice-grid">{moods.map((x) => <button className={mood === x ? "choice active" : "choice"} onClick={() => setMood(x)} data-testid={`mood-${x.toLowerCase().replaceAll(" ", "-")}`} key={x}>{x}</button>)}</div></div><div className="split-questions"><div className="question"><label>How many people?</label><div className="stepper"><button onClick={() => setPeople(Math.max(1, people - 1))} data-testid="people-minus"><Minus size={15} /></button><strong data-testid="people-count">{people}</strong><button onClick={() => setPeople(people + 1)} data-testid="people-plus"><Plus size={15} /></button></div></div><div className="question"><label>Budget</label><div className="budget-input"><span>Rs.</span><input value={budget} onChange={(e) => setBudget(e.target.value)} data-testid="budget-input" /></div></div></div><div className="question"><label>Any dietary preferences?</label><select value={dietary} onChange={(e) => setDietary(e.target.value)} data-testid="dietary-select"><option>No preference</option><option>Eggless</option><option>Less sweet</option><option>Gluten conscious</option></select></div><button className="button primary wide" onClick={runMatch} disabled={loading} data-testid="find-match-button">{loading ? "Finding your match…" : <>Find my perfect match <ArrowRight size={17} /></>}</button></div></section>
      {match && <section className="result-section" id="match-result"><div className="result-card"><div className="result-image"><img src={match.product.image} alt={match.product.name} data-testid="match-product-image" /><span>YOUR PERFECT MATCH</span></div><div className="result-copy"><p className="eyebrow">A NOTE FROM THE BAKER</p><h2>{match.product.name}</h2><p className="result-description">{match.explanation}</p><p className="story">“{match.product.story}”</p><div className="result-meta"><span>Serves {match.product.serves}</span><b>Rs. {match.product.price.toLocaleString()}</b></div><button className="button primary" onClick={() => addToCart(match.product)} data-testid="add-match-to-cart">Add to my box <ShoppingBag size={17} /></button></div></div></section>}
      <section className="box-section" id="box"><div className="box-heading"><div><p className="eyebrow">02 / BUILD YOUR BOX</p><h2>A little bit of<br /><em>everything.</em></h2></div><p>Choose your mix. We’ll do the wrapping.</p></div><div className="box-layout"><div className="box-visual"><div className="box-label">YOUR<br /><b>BAKE BOX</b></div><div className="box-items">{products.map((p, i) => <div className={`box-piece piece-${i}`} key={p.id}><img src={p.image} alt={p.name} /><span>{i === 0 ? 1 : i === 1 ? 2 : i === 2 ? 1 : 2}×</span></div>)}</div></div><div className="box-list">{products.map((p, i) => <div className="box-row" key={p.id}><img src={p.image} alt={p.name} /><div><b>{i === 0 ? 1 : i === 1 ? 2 : i === 2 ? 1 : 2}× {p.name}</b><small>handmade in small batches</small></div><strong>Rs. {Math.round(p.price / (i === 0 ? 1 : i === 1 ? 3 : i === 2 ? 1 : 4)).toLocaleString()}</strong></div>)}<div className="box-total"><span>Box total</span><b>Rs. {Math.round(box).toLocaleString()}</b></div><button className="button primary wide" onClick={() => setCart(products)} data-testid="add-box-to-cart">Add this box to cart <ShoppingBag size={17} /></button></div></div></section>
      <section className="stories" id="stories"><div><p className="eyebrow">03 / STORY BEHIND THE BAKE</p><h2>Good things<br /><em>take time.</em></h2><p className="story-lead">Every bake has a mood, a memory, a reason to be shared. Here are a few of ours.</p><a className="inline-link" href="https://www.instagram.com/treatsandtemptationbysk/" target="_blank" rel="noreferrer" data-testid="instagram-link">See more on Instagram <Instagram size={17} /></a></div><div className="story-grid">{products.slice(1, 4).map((p) => <article className="story-card" key={p.id}><img src={p.image} alt={p.name} /><div><p className="eyebrow">THE {p.name.toUpperCase()}</p><p>{p.story}</p></div></article>)}</div></section>
    </main>
    <footer><div className="brand"><span className="brand-mark">SK</span><span>Treats &<br /><b>Temptation</b></span></div><span>Made with butter, time & a little bit of magic.</span><a href="https://www.instagram.com/treatsandtemptationbysk/" target="_blank" rel="noreferrer" data-testid="footer-instagram">@treatsandtemptationbysk <Instagram size={16} /></a></footer>
    {chatOpen && <div className="chat-drawer" data-testid="baker-chat-drawer"><div className="chat-header"><div><p className="eyebrow">AI BAKER CHAT</p><b>Ask SK anything sweet</b></div><button onClick={() => setChatOpen(false)} data-testid="close-baker-chat"><X /></button></div><div className="chat-messages">{chat.map((m, i) => <div className={`chat-bubble ${m.role}`} key={i} data-testid={`chat-message-${i}`}>{m.text}</div>)}</div><div className="chat-input"><input value={message} onChange={(e) => setMessage(e.target.value)} onKeyDown={(e) => e.key === "Enter" && sendChat()} placeholder="e.g. something for 8 people…" data-testid="baker-chat-input" /><button onClick={sendChat} data-testid="send-baker-chat"><ArrowRight /></button></div><button className="whatsapp-button" onClick={whatsapp} data-testid="chat-whatsapp-order">Order through WhatsApp <MessageCircle size={16} /></button></div>}
  </div>;
}
export default App;